# Generated by Django 4.1.7 on 2023-05-08 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("accounts", "0001_initial"),
        ("debts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teams.workspace"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.account"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teams.workspace"
            ),
        ),
    ]
