# Generated by Django 4.1.7 on 2023-04-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="workspace_uid",
            field=models.CharField(
                default="372345a627734aefbe43ad8026652b46", max_length=50
            ),
        ),
    ]
