# Generated by Django 4.1.7 on 2023-05-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="workspace_uid",
            field=models.CharField(
                default="dac5a2403269414c9fd830b4fcac0ff7", max_length=50
            ),
        ),
    ]
