# Generated by Django 4.1.7 on 2023-04-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='workspace_uid',
            field=models.CharField(default='ac9385a1ac0d4eb79d222ceacaf38bc9', max_length=50),
        ),
    ]
