# Generated by Django 4.1.7 on 2023-04-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_workspace_workspace_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='workspace_uid',
            field=models.CharField(default='afcc189a4b91459392ef70c121ddff98', max_length=50),
        ),
    ]
