# Generated by Django 4.1.7 on 2023-04-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_workspace_workspace_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='workspace_uid',
            field=models.CharField(default='0e0c212b625f485481457567dfecc7b6', max_length=50),
        ),
    ]
