# Generated by Django 4.1.7 on 2023-04-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_workspace_workspace_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='workspace_uid',
            field=models.CharField(default='051bf07b8d7443f49ebdda05bf5ef99e', max_length=50),
        ),
    ]
