# Generated by Django 4.1.7 on 2023-03-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='567ad4c1b1654628a35f0d947dfb67d0', max_length=40),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='public_id',
            field=models.CharField(default='bbba196e3aa742358e4e7ca25688c335', max_length=40),
        ),
    ]
