# Generated by Django 4.1.7 on 2023-03-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdevice',
            name='key',
            field=models.CharField(default='W2AWN4HUHLIJDMRB34B6TCO6UH52TRXO', max_length=100),
        ),
    ]
