# Generated by Django 4.1.7 on 2023-04-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdevice',
            name='key',
            field=models.CharField(default='T7J5FGA35TDJAIDN6GHE2CXVLM3YBXLK', max_length=100),
        ),
    ]
