# Generated by Django 4.1.7 on 2023-04-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at'], 'verbose_name': 'subscriber plan', 'verbose_name_plural': 'subscriber plans'},
        ),
        migrations.AlterField(
            model_name='otpdevice',
            name='key',
            field=models.CharField(default='CKXUFUYR6DVSNKIJDPKPSM3IKVCYBWDH', max_length=100),
        ),
        migrations.AlterModelTable(
            name='package',
            table='SubscriberPlans',
        ),
    ]
