# Generated by Django 4.1.7 on 2023-04-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_paying',
        ),
        migrations.AlterField(
            model_name='otpdevice',
            name='key',
            field=models.CharField(default='VPO5ZIALEWDQPFOMW5VUBILX5PV6J45V', max_length=100),
        ),
    ]
