# Generated by Django 4.1.7 on 2023-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='71eb8dea1fb84cc98859d4354974d75e', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default='c6265a64aba94f91a4cf43b719bfed34', max_length=40),
        ),
    ]
