# Generated by Django 4.1.7 on 2023-05-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpdevice",
            name="key",
            field=models.CharField(
                default="B55WIJHP64ORYKQ3UAERCV5D6IKXV7FZ", max_length=100
            ),
        ),
    ]
