# Generated by Django 4.1.7 on 2023-03-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='85435128538746f9b1c5f049218edd64', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default='4ce7d6f6cab2465dbdd5933014c8143f', max_length=40),
        ),
    ]
