# Generated by Django 4.1.7 on 2023-04-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_otpdevice_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdevice',
            name='key',
            field=models.CharField(default='F3SV7LHDFES7OTQ4GH3VOBDE2MB5TJ6Z', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
