# Generated by Django 4.1.7 on 2023-04-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_otpdevice_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdevice',
            name='key',
            field=models.CharField(default='JA2VXX7LUTHTI5DFRXE5KFQTZNTIYFLI', max_length=100),
        ),
    ]
