# Generated by Django 4.1.7 on 2023-04-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_otpdevice_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdevice',
            name='key',
            field=models.CharField(default='436XNK2PUSAABLVVMKHVQOLUPW7EUMVR', max_length=100),
        ),
    ]
