# Generated by Django 4.1.7 on 2023-03-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_public_id_alter_user_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='7f21d2ebf8ba4266aa48740abea101fc', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default='0cd8a62465b64b208f7dc1bc51a65ea3', max_length=40),
        ),
    ]
