# Generated by Django 4.1.7 on 2023-04-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_is_paying_alter_otpdevice_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_paid_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otpdevice',
            name='key',
            field=models.CharField(default='ICMT46H2VGWPWLUU6RKQK7UYAWDTQN47', max_length=100),
        ),
    ]
