# Generated by Django 4.1.7 on 2023-03-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_userlog_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='f898251306064aae9f57b06f44defadc', max_length=40),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='public_id',
            field=models.CharField(default='a73e1d5cdac84eecb04e93eb801561d8', max_length=40),
        ),
    ]
