# Generated by Django 4.1.7 on 2023-03-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_public_id_alter_workspace_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='public_id',
            field=models.CharField(default='242a83c43a614bae80ccb60da9130b9a', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='e1150ae83e814b33ad7843848df98bd7', max_length=40),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='public_id',
            field=models.CharField(default='be40f6ddde9e4238b708e6d643a61d58', max_length=40),
        ),
    ]
