# Generated by Django 4.1.7 on 2023-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_account_limit_profile_ai_predictions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pdf_gen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='5dee1a9d193546d8a516d53b8d34e7d2', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default='3b6ac39ba0d94fb5afda4ddc37b7c3cd', max_length=40),
        ),
    ]
