# Generated by Django 4.1.7 on 2023-04-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_otpdevice_key_alter_package_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdevice',
            name='key',
            field=models.CharField(default='Y4U4EIJAGJXNTAJ5VBFUZ3BF7U7ZCPY2', max_length=100),
        ),
    ]
