# Generated by Django 4.1.7 on 2023-03-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userlog_public_id_alter_profile_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='8d2367819c7d41448e947cda6c19ed96', max_length=40),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='public_id',
            field=models.CharField(default='3c714ae7db53446dbca544a0c4c983f2', max_length=40),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='public_id',
            field=models.CharField(default='3add1d20c3fe42cb9a9a9873bfca9ccf', max_length=40),
        ),
    ]
