# Generated by Django 4.1.7 on 2023-04-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_otpdevice_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdevice',
            name='key',
            field=models.CharField(default='BFQNSNQIMJCCBYRNB2FQTCAONLFXGS7F', max_length=100),
        ),
    ]
