# Generated by Django 4.1.7 on 2023-04-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_otpdevice_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpdevice",
            name="key",
            field=models.CharField(
                default="OQTEJ2FLJKPN4IQPVHM26Y6BYOMHMZB5", max_length=100
            ),
        ),
    ]
