# Generated by Django 4.1.7 on 2023-03-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_public_id_alter_userlog_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='62852019a84142f18417f039c35d5e8a', max_length=40),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='public_id',
            field=models.CharField(default='a9c73abbe07f482a85ae7d00025a506b', max_length=40),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='public_id',
            field=models.CharField(default='4de084d968a54407b7bd52e5928c643c', max_length=40),
        ),
    ]
