# Generated by Django 4.1.7 on 2023-03-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_public_id_alter_userlog_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='public_id',
        ),
    ]
