# Generated by Django 4.1.7 on 2023-03-30 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_owner', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mpesa user',
                'verbose_name_plural': 'mpesa users',
                'db_table': 'MpesaUsers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uid', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.mpesapaymentmethod')),
            ],
            options={
                'verbose_name': 'mpesa payment',
                'verbose_name_plural': 'mpesa payments',
                'db_table': 'MpesaPayments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_month', models.PositiveSmallIntegerField()),
                ('expiration_year', models.PositiveSmallIntegerField()),
                ('cvc', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'card user',
                'verbose_name_plural': 'card users',
                'db_table': 'CardUsers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uid', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.cardpaymentmethod')),
            ],
            options={
                'verbose_name': 'card payment',
                'verbose_name_plural': 'card payments',
                'db_table': 'CardPayments',
                'ordering': ['-created_at'],
            },
        ),
    ]
