# Generated by Django 4.1.7 on 2023-04-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planbilling',
            name='account_ref',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
