# Generated by Django 4.1.7 on 2023-06-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("accounts", models.BooleanField(default=False)),
                ("no_of_accounts", models.IntegerField(default=0)),
                ("budgets", models.BooleanField(default=False)),
                ("no_of_budgets", models.IntegerField(default=0)),
                ("targets", models.BooleanField(default=False)),
                ("no_of_targets", models.IntegerField(default=0)),
                ("invoices", models.BooleanField(default=False)),
                ("no_of_invoices", models.IntegerField(default=0)),
                ("pdf_reports", models.BooleanField(default=False)),
                ("ai_assistant", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "subscriber plan",
                "verbose_name_plural": "subscriber plans",
                "db_table": "SubscriberPlans",
                "ordering": ["-created_at"],
            },
        ),
    ]
