# Generated by Django 4.1.7 on 2023-03-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='public_id',
            field=models.CharField(default='cf5def2e988b4e8fb7a1346b671e71ce', max_length=40),
        ),
        migrations.AlterField(
            model_name='budget',
            name='public_id',
            field=models.CharField(default='516c2d20659143ef894cfeaa6406c34a', max_length=40),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='public_id',
            field=models.CharField(default='9211e07bd08c445290994afdc75995e8', max_length=40),
        ),
        migrations.AlterField(
            model_name='category',
            name='public_id',
            field=models.CharField(default='0555d18677154239bd0f883492b946eb', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='4207cd8b55234426ae399bcea30bf739', max_length=40),
        ),
        migrations.AlterField(
            model_name='reportaccount',
            name='public_id',
            field=models.CharField(default='4e4936e05997442da19fba1ab81a899e', max_length=40),
        ),
        migrations.AlterField(
            model_name='reportcategory',
            name='public_id',
            field=models.CharField(default='bca3a90eebf84637896b61038717a7c7', max_length=40),
        ),
        migrations.AlterField(
            model_name='reporttransaction',
            name='public_id',
            field=models.CharField(default='7a7c8cb1463645f8bef680be29704192', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='public_id',
            field=models.CharField(default='ffbdb1f00d7a414581c1390221be2264', max_length=40),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='public_id',
            field=models.CharField(default='d56eea19c68441a5af389dd9809d8e41', max_length=40),
        ),
    ]
