# Generated by Django 4.1.7 on 2023-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='public_id',
            field=models.CharField(default='a44c66efdbc94c7593dbfff86ce24b25', max_length=40),
        ),
        migrations.AlterField(
            model_name='budget',
            name='public_id',
            field=models.CharField(default='60db11550ae74828974b4f3540f579a9', max_length=40),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='public_id',
            field=models.CharField(default='a4e0ba1403b04a2dba26edd017013485', max_length=40),
        ),
        migrations.AlterField(
            model_name='category',
            name='public_id',
            field=models.CharField(default='b66fdd7ba79541d7ab54d087e20cf202', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='2657e1bfce9648e794c0544f6d5251cd', max_length=40),
        ),
        migrations.AlterField(
            model_name='reportcategory',
            name='public_id',
            field=models.CharField(default='709e5314b5e443eabf508629415dc4c6', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='public_id',
            field=models.CharField(default='54f84094b6b04d198ef89f856abf41c8', max_length=40),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='public_id',
            field=models.CharField(default='e89217c277a7455ca20cb59041109421', max_length=40),
        ),
    ]
