# Generated by Django 4.1.7 on 2023-03-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='public_id',
            field=models.CharField(default='9a20d76dccb94fa0885d11f7e824792b', max_length=40),
        ),
        migrations.AlterField(
            model_name='budget',
            name='public_id',
            field=models.CharField(default='ab23679b34204ca88780cfdfc3138055', max_length=40),
        ),
        migrations.AlterField(
            model_name='category',
            name='public_id',
            field=models.CharField(default='f97e7085762844beb69eeeef35f25acf', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='105179b66d74422682dadbc0ce4ecbe8', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='public_id',
            field=models.CharField(default='05516fc18fbd4e1888f874957733c51a', max_length=40),
        ),
    ]
