# Generated by Django 4.1.7 on 2023-03-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='public_id',
            field=models.CharField(default='df097a4f224b4161a877ef41f3e379cf', max_length=40),
        ),
        migrations.AlterField(
            model_name='budget',
            name='public_id',
            field=models.CharField(default='5fedf1ffadf2440285a9e39291a68d07', max_length=40),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='public_id',
            field=models.CharField(default='13929551961e44dd99a589b5ebd50d27', max_length=40),
        ),
        migrations.AlterField(
            model_name='category',
            name='public_id',
            field=models.CharField(default='49145d6dae1a451c8c036f90c4383d48', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='eb1b67a6a0dd4b8593dcf2c8d7897eac', max_length=40),
        ),
        migrations.AlterField(
            model_name='reportcategory',
            name='public_id',
            field=models.CharField(default='4068f49ddc8e4331b619b35eb72f37dc', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='public_id',
            field=models.CharField(default='0e58e413e869497d83c7d91a30a8d1d1', max_length=40),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='public_id',
            field=models.CharField(default='975a7481d1c34fbabb6454fa6a397514', max_length=40),
        ),
    ]
