# Generated by Django 4.1.7 on 2023-03-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
    ]
