# Generated by Django 4.1.7 on 2023-03-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_account_public_id_alter_budget_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='public_id',
            field=models.CharField(default='a163b4319f3447b2ba90630d5499cf86', max_length=40),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='public_id',
            field=models.CharField(default='b4b940b9547c4fd987df60a33f8eca1f', max_length=40),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='public_id',
            field=models.CharField(default='8ac8047b1d3e44889f73f316ffe31321', max_length=40),
        ),
        migrations.AlterField(
            model_name='category',
            name='public_id',
            field=models.CharField(default='4872e6503f5d4b5da79097d0bb2091a7', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='9b0ebe481a6f4d14a4b6c82ca6a9678e', max_length=40),
        ),
        migrations.AlterField(
            model_name='reportcategory',
            name='public_id',
            field=models.CharField(default='5f133080602847c4b9c2519cb9baf2a8', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='public_id',
            field=models.CharField(default='6a6fdaa05bf54a3ba987f26e3515b98f', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='public_id',
            field=models.CharField(default='70ea34ce1f2242ffa49a3f6c25e41a6f', max_length=40),
        ),
    ]
