# Generated by Django 4.1.7 on 2023-03-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_account_public_id_alter_budget_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='public_id',
            field=models.CharField(default='ddcdbb2328aa403f99e79a13e7a64a89', max_length=40),
        ),
        migrations.AlterField(
            model_name='budget',
            name='public_id',
            field=models.CharField(default='fcca0c2ea0ff4c7cb0072cbfe8c500dc', max_length=40),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='public_id',
            field=models.CharField(default='10c602afaabf476ea05d055a905cd4e4', max_length=40),
        ),
        migrations.AlterField(
            model_name='category',
            name='public_id',
            field=models.CharField(default='10ded7e8e978495a9ccdda73d9623967', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='4b08bc97da814a158a959a8707d800e4', max_length=40),
        ),
        migrations.AlterField(
            model_name='reportcategory',
            name='public_id',
            field=models.CharField(default='1dc86a8973f945a0ad4aee4034495277', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='public_id',
            field=models.CharField(default='4e9ba1a0d59443c0afe9680477492132', max_length=40),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='public_id',
            field=models.CharField(default='c495c03b58424fffabe3d8ea8b689d5b', max_length=40),
        ),
    ]
