# Generated by Django 4.1.7 on 2023-03-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_account_public_id_alter_budget_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='reportcategory',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='transactioncategory',
            name='public_id',
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_end_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_start_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.CharField(max_length=50),
        ),
    ]
