# Generated by Django 4.1.7 on 2023-05-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
                ("category_description", models.TextField()),
            ],
            options={
                "verbose_name": "product category",
                "verbose_name_plural": "product categories",
                "db_table": "ProductCategories",
            },
        ),
        migrations.CreateModel(
            name="ProductSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
                ("category_description", models.TextField()),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "product sub category",
                "verbose_name_plural": "product sub categories",
                "db_table": "ProductSubCategories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("buying_price", models.FloatField(default=0.0)),
                ("selling_price", models.FloatField(default=0.0)),
                ("current_stock_level", models.IntegerField(default=0)),
                ("units_sold", models.IntegerField(default=0)),
                ("reorder_level", models.IntegerField(blank=True, default=0)),
                ("reorder_quantity", models.IntegerField(blank=True, default=0)),
                ("supplier_name", models.CharField(max_length=255)),
                ("supplier_phone_number", models.CharField(max_length=20)),
                ("supplier_email", models.CharField(blank=True, max_length=150)),
                ("profit_generated", models.FloatField(blank=True, default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.productcategory",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.productsubcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "db_table": "Products",
                "ordering": ["-created_at"],
            },
        ),
    ]
