# Generated by Django 4.1.7 on 2023-06-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Operating Activity", "Operating"),
                            ("Investing Activity", "Investing"),
                            ("Financing Activity", "Financing"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "business activity",
                "verbose_name_plural": "Business activities",
                "db_table": "BusinessActivities",
            },
        ),
        migrations.CreateModel(
            name="CashFlowItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("is_income", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.businessactivity",
                    ),
                ),
            ],
            options={
                "verbose_name": "cash flow item",
                "verbose_name_plural": "cash flow items",
                "db_table": "CashFlowItems",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashFlowStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statement_uid",
                    models.CharField(
                        default="39e488a5b8d6442dbfd7157e2b47b716", max_length=50
                    ),
                ),
                ("begin_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "cash flow statement",
                "verbose_name_plural": "cash flow statements",
                "db_table": "CashFlowStatements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashFlowRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement_uid", models.CharField(max_length=50)),
                ("amount", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.cashflowitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "cash flow record",
                "verbose_name_plural": "cash flow records",
                "db_table": "CashFlowRecords",
                "ordering": ["-created_at"],
            },
        ),
    ]
